import Head from 'next/head'
import { Main } from '../src/pages/Main'
import '../styles/Home.module.css'
import { getCoins, getTrendingCoins } from 'src/shared/api'
import { initializeStore } from 'src/app'
import { paginationModel } from 'src/entities/pagination'

export default function Home({data,coins}:any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main trendCoins={data} coins={coins}/>
      </main>
    </>
  )
}

export async function getStaticProps(){
  const data = await getTrendingCoins('USD')
  const coins = await getCoins('USD')
  const reduxStore = initializeStore({})
  reduxStore.dispatch(paginationModel.actions.setCurrentItems(coins.slice(0, 10)))
  return {
    props: {data,coins, initialReduxState: reduxStore.getState()},
    revalidate: 10,
  }
}